//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientUtility.WSAddData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAddData.IUrbanWaterAddEntry")]
    public interface IUrbanWaterAddEntry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanWaterAddEntry/GetEntryData", ReplyAction="http://tempuri.org/IUrbanWaterAddEntry/GetEntryDataResponse")]
        bool GetEntryData(string id, string dt, string reading);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanWaterAddEntry/GetEntryData", ReplyAction="http://tempuri.org/IUrbanWaterAddEntry/GetEntryDataResponse")]
        System.Threading.Tasks.Task<bool> GetEntryDataAsync(string id, string dt, string reading);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrbanWaterAddEntryChannel : ClientUtility.WSAddData.IUrbanWaterAddEntry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrbanWaterAddEntryClient : System.ServiceModel.ClientBase<ClientUtility.WSAddData.IUrbanWaterAddEntry>, ClientUtility.WSAddData.IUrbanWaterAddEntry {
        
        public UrbanWaterAddEntryClient() {
        }
        
        public UrbanWaterAddEntryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrbanWaterAddEntryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrbanWaterAddEntryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrbanWaterAddEntryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetEntryData(string id, string dt, string reading) {
            return base.Channel.GetEntryData(id, dt, reading);
        }
        
        public System.Threading.Tasks.Task<bool> GetEntryDataAsync(string id, string dt, string reading) {
            return base.Channel.GetEntryDataAsync(id, dt, reading);
        }
    }
}
